fix: build error which has been caused by unocss typings
node_modules/@unocss/core/dist/index.d.ts:1:34 - error TS2307: Cannot find module 'unconfig' or its corresponding type declarations.